<!-- Generated: 2026-03-03T10:54:09.216Z -->
        <script setup lang="ts">
        import articleTheme from '~/components/Theme/article-theme.vue'
        import type { NavItem } from 'kecare'
        const article = {"lang":"ja-JP","title":"ジェネレーターCLI","html":"<div class=\"kecare\"><p>Kecareは、開発プロセスを簡素化する便利なコマンドを提供しています：</p>\n<h3 id=\"サイトの構築\">サイトの構築</h3>\n<p>テーマディレクトリを追加した後、以下のコマンドを実行するだけでサイトを構築できます：</p>\n<pre><code class=\"language-bash\">kecare gen\n</code></pre>\n<p>保存したテーマのパスを使用して自動的に構築されます。</p>\n<h3 id=\"サーバーを起動する\">サーバーを起動する</h3>\n<p>サーバーを起動する</p>\n<pre><code class=\"language-bash\">kecare dev\n</code></pre>\n<p>これにより、テーマの開発サーバー（例：Nuxt dev）が自動的に起動し、<code>http://localhost:3000</code> でアクセスできます。</p>\n<h2 id=\"faq先に命を救ってニャン\">FAQ（先に命を救ってニャン）</h2>\n<p>私にはわかりません、ごめんなさいにゃん</p>\n</div>","menu":"test","isOriginalLang":false,"desc":"Kecare 提供了便捷的命令来简化你的开发流程： ### 构建站点 添加主题目录后，直接运行以下命令即可构建站点： ```bash kecare gen ``` 它会自动使用你保存的主题路径进行构建。 ### 启动服务器 启动服务器 ``...","hash":"fddd58bb","relativePath":"/生成器CLI.md","frontMatter":{"cover":"https://pichost.cloud/files/944b71a32407dd671f9d09296c439efb3cfeb95341fd87cc9490470710bbbc76.webp","title":"生成器CLI","menu":"test","tags":[],"desc":"Kecare 提供了便捷的命令来简化你的开发流程： ### 构建站点 添加主题目录后，直接运行以下命令即可构建站点： ```bash kecare gen ``` 它会自动使用你保存的主题路径进行构建。 ### 启动服务器 启动服务器 ``...","translate":["zh-CN","en-US","ja-JP"]},"cover":"https://pichost.cloud/files/944b71a32407dd671f9d09296c439efb3cfeb95341fd87cc9490470710bbbc76.webp","rawMarkdown":"\r\nKecare 提供了便捷的命令来简化你的开发流程：\r\n\r\n###  构建站点\r\n添加主题目录后，直接运行以下命令即可构建站点：\r\n```bash\r\nkecare gen\r\n```\r\n它会自动使用你保存的主题路径进行构建。\r\n\r\n### 启动服务器\r\n启动服务器\r\n```bash\r\nkecare dev\r\n```\r\n它会自动启动主题的开发服务器（如 Nuxt dev），你可以在 `http://localhost:3000` 访问。\r\n\r\n\r\n## FAQ（先救命喵）\r\n\r\n我不知道喵，对不起喵\r\n\r\n"}
        const navItems:NavItem[] = [{"text":"入门指南","level":1,"items":[{"text":"Kecare从这里开始喵","link":"./70e6923c","level":2},{"text":"快速开始","link":"./95bb100b","level":2},{"text":"项目结构约定","link":"./a3b16d10","level":2}]},{"text":"基本操作","level":1,"items":[{"text":"写作","link":"./6e8c5f0b","level":2},{"text":"Markdown扩展","link":"./b40d18d1","level":2},{"text":"菜单系统","link":"./4ee23999","level":2},{"text":"国际化处理","link":"./493f5fa2","level":2}]},{"text":"部署","level":1,"items":[{"text":"GitHub Pages","link":"./39f6b230","level":2}]},{"text":"进阶","level":1,"items":[{"text":"生成器 CLI","level":2,"items":[{"text":"生成器CLI","link":"./fddd58bb","level":3},{"text":"自定义生成器CLI","link":"./9e192d60","level":3}]}]},{"text":"贡献与协作","level":1,"items":[{"text":"贡献指南","link":"./43fc313b","level":2}]}]
        </script>
        <template>
        <articleTheme :article="article"
                       :navItems="navItems"
                       />
        </template>
