<!-- Generated: 2026-03-03T10:54:06.816Z -->
        <script setup lang="ts">
        import articleTheme from '~/components/Theme/article-theme.vue'
        import type { NavItem } from 'kecare'
        const article = {"lang":"zh-CN","title":"写作","html":"<div class=\"kecare\"><h1 id=\"写作\">写作</h1>\n<p>在 Kecare 中，文章有一个固定存放位置喵：</p>\n<ul>\n<li>文章目录：<strong>主题目录/.kecare/articles/</strong></li>\n<li>文件类型：目前仅支持 <strong><code>*.md</code></strong></li>\n<li>推荐命名：使用稳定、可读的英文文件名（例如 <strong><code>getting-started.md</code></strong>），避免频繁改名捏</li>\n</ul>\n<p>目前只支持 Markdown（<strong>.md</strong>）文章。后续会逐步支持更多“笔记格式/文件类型”的捏。</p>\n<h2 id=\"1-新建文章文件\">1. 新建文章文件</h2>\n<p>在 <strong>主题目录/.kecare/articles/</strong> 下新建一个 Markdown 文件，例如：</p>\n<ul>\n<li><strong><code>hello-kecare.md</code></strong></li>\n<li><strong><code>my-first-post.md</code></strong></li>\n</ul>\n<h2 id=\"2-写正文内容\">2. 写正文内容</h2>\n<p>你可以像写普通 Markdown 一样写正文内容，写完记得保存喵~</p>\n<p>下面给你一个最小示例喵~</p>\n<pre><code class=\"language-markdown\">---\ntitle: Hello Kecare\ndate: 2026-01-22 12:00:00\ntags:\n  - kecare\ndesc: 这是我的第一篇 Kecare 文章喵~\nauthor: Pamper\nmenu: test\ntranslate: [&#39;zh-CN&#39;, &#39;en-US&#39;, &#39;ja-JP&#39;]\n---\n\n# Hello Kecare\n\n这是一段正文内容喵~\n\n- 支持 Markdown 标题\n- 支持列表\n- 支持代码块\n\n```ts\nconsole.log(&quot;喵喵喵喵喵喵喵喵喵喵喵~&quot;);\n```\n</code></pre>\n<h2 id=\"3-运行\">3. 运行</h2>\n<p>写完文章后，需要运行生成器才能在浏览器里看到更新喵。</p>\n</div>","isOriginalLang":true,"menu":"test","desc":"# 写作 在 Kecare 中，文章有一个固定存放位置喵： - 文章目录：**主题目录/.kecare/articles/** - 文件类型：目前仅支持 **`*.md`** - 推荐命名：使用稳定、可读的英文文件名（例如 **`getti...","hash":"6e8c5f0b","relativePath":"/写作.md","frontMatter":{"cover":"https://pichost.cloud/files/944b71a32407dd671f9d09296c439efb3cfeb95341fd87cc9490470710bbbc76.webp","title":"写作","menu":"test","tags":[],"desc":"# 写作 在 Kecare 中，文章有一个固定存放位置喵： - 文章目录：**主题目录/.kecare/articles/** - 文件类型：目前仅支持 **`*.md`** - 推荐命名：使用稳定、可读的英文文件名（例如 **`getti...","translate":["zh-CN","en-US","ja-JP"]},"cover":"https://pichost.cloud/files/944b71a32407dd671f9d09296c439efb3cfeb95341fd87cc9490470710bbbc76.webp","rawMarkdown":"\r\n# 写作\r\n\r\n在 Kecare 中，文章有一个固定存放位置喵：\r\n\r\n- 文章目录：**主题目录/.kecare/articles/**\r\n- 文件类型：目前仅支持 **`*.md`**\r\n- 推荐命名：使用稳定、可读的英文文件名（例如 **`getting-started.md`**），避免频繁改名捏\r\n\r\n目前只支持 Markdown（**.md**）文章。后续会逐步支持更多“笔记格式/文件类型”的捏。\r\n\r\n## 1. 新建文章文件\r\n\r\n在 **主题目录/.kecare/articles/** 下新建一个 Markdown 文件，例如：\r\n\r\n- **`hello-kecare.md`**\r\n- **`my-first-post.md`**\r\n\r\n## 2. 写正文内容\r\n\r\n你可以像写普通 Markdown 一样写正文内容，写完记得保存喵~\r\n\r\n下面给你一个最小示例喵~\r\n\r\n````markdown\r\n---\r\ntitle: Hello Kecare\r\ndate: 2026-01-22 12:00:00\r\ntags:\r\n  - kecare\r\ndesc: 这是我的第一篇 Kecare 文章喵~\r\nauthor: Pamper\r\nmenu: test\r\ntranslate: ['zh-CN', 'en-US', 'ja-JP']\r\n---\r\n\r\n# Hello Kecare\r\n\r\n这是一段正文内容喵~\r\n\r\n- 支持 Markdown 标题\r\n- 支持列表\r\n- 支持代码块\r\n\r\n```ts\r\nconsole.log(\"喵喵喵喵喵喵喵喵喵喵喵~\");\r\n```\r\n````\r\n\r\n## 3. 运行\r\n\r\n写完文章后，需要运行生成器才能在浏览器里看到更新喵。\r\n"}
        const navItems:NavItem[] = [{"text":"入门指南","level":1,"items":[{"text":"Kecare从这里开始喵","link":"./70e6923c","level":2},{"text":"快速开始","link":"./95bb100b","level":2},{"text":"项目结构约定","link":"./a3b16d10","level":2}]},{"text":"基本操作","level":1,"items":[{"text":"写作","link":"./6e8c5f0b","level":2},{"text":"Markdown扩展","link":"./b40d18d1","level":2},{"text":"菜单系统","link":"./4ee23999","level":2},{"text":"国际化处理","link":"./493f5fa2","level":2}]},{"text":"部署","level":1,"items":[{"text":"GitHub Pages","link":"./39f6b230","level":2}]},{"text":"进阶","level":1,"items":[{"text":"生成器 CLI","level":2,"items":[{"text":"生成器CLI","link":"./fddd58bb","level":3},{"text":"自定义生成器CLI","link":"./9e192d60","level":3}]}]},{"text":"贡献与协作","level":1,"items":[{"text":"贡献指南","link":"./43fc313b","level":2}]}]
        </script>
        <template>
        <articleTheme :article="article"
                       :navItems="navItems"
                       />
        </template>
