<!-- Generated: 2026-03-03T10:54:07.941Z -->
        <script setup lang="ts">
        import articleTheme from '~/components/Theme/article-theme.vue'
        import type { NavItem } from 'kecare'
        const article = {"lang":"en-US","title":"Generator CLI","html":"<div class=\"kecare\"><p>Kecare offers convenient commands to streamline your development process:</p>\n<h3 id=\"building-the-site\">Building the Site</h3>\n<p>After adding the theme directory, you can build the site directly by running the following command:</p>\n<pre><code class=\"language-bash\">kecare gen\n</code></pre>\n<p>It will automatically use the theme path you saved to build the site.</p>\n<h3 id=\"start-the-server\">Start the Server</h3>\n<p>Start the server</p>\n<pre><code class=\"language-bash\">kecare dev\n</code></pre>\n<p>It will automatically start the theme&#39;s development server (e.g., Nuxt dev), and you can access it at <code>http://localhost:3000</code>.</p>\n<h2 id=\"faq-first-aid-for-cats\">FAQ (First Aid for Cats)</h2>\n<p>I don&#39;t know meow, sorry meow</p>\n</div>","menu":"test","isOriginalLang":false,"desc":"Kecare 提供了便捷的命令来简化你的开发流程： ### 构建站点 添加主题目录后，直接运行以下命令即可构建站点： ```bash kecare gen ``` 它会自动使用你保存的主题路径进行构建。 ### 启动服务器 启动服务器 ``...","hash":"fddd58bb","relativePath":"/生成器CLI.md","frontMatter":{"cover":"https://pichost.cloud/files/944b71a32407dd671f9d09296c439efb3cfeb95341fd87cc9490470710bbbc76.webp","title":"生成器CLI","menu":"test","tags":[],"desc":"Kecare 提供了便捷的命令来简化你的开发流程： ### 构建站点 添加主题目录后，直接运行以下命令即可构建站点： ```bash kecare gen ``` 它会自动使用你保存的主题路径进行构建。 ### 启动服务器 启动服务器 ``...","translate":["zh-CN","en-US","ja-JP"]},"cover":"https://pichost.cloud/files/944b71a32407dd671f9d09296c439efb3cfeb95341fd87cc9490470710bbbc76.webp","rawMarkdown":"\r\nKecare 提供了便捷的命令来简化你的开发流程：\r\n\r\n###  构建站点\r\n添加主题目录后，直接运行以下命令即可构建站点：\r\n```bash\r\nkecare gen\r\n```\r\n它会自动使用你保存的主题路径进行构建。\r\n\r\n### 启动服务器\r\n启动服务器\r\n```bash\r\nkecare dev\r\n```\r\n它会自动启动主题的开发服务器（如 Nuxt dev），你可以在 `http://localhost:3000` 访问。\r\n\r\n\r\n## FAQ（先救命喵）\r\n\r\n我不知道喵，对不起喵\r\n\r\n"}
        const navItems:NavItem[] = [{"text":"入门指南","level":1,"items":[{"text":"Kecare从这里开始喵","link":"./70e6923c","level":2},{"text":"快速开始","link":"./95bb100b","level":2},{"text":"项目结构约定","link":"./a3b16d10","level":2}]},{"text":"基本操作","level":1,"items":[{"text":"写作","link":"./6e8c5f0b","level":2},{"text":"Markdown扩展","link":"./b40d18d1","level":2},{"text":"菜单系统","link":"./4ee23999","level":2},{"text":"国际化处理","link":"./493f5fa2","level":2}]},{"text":"部署","level":1,"items":[{"text":"GitHub Pages","link":"./39f6b230","level":2}]},{"text":"进阶","level":1,"items":[{"text":"生成器 CLI","level":2,"items":[{"text":"生成器CLI","link":"./fddd58bb","level":3},{"text":"自定义生成器CLI","link":"./9e192d60","level":3}]}]},{"text":"贡献与协作","level":1,"items":[{"text":"贡献指南","link":"./43fc313b","level":2}]}]
        </script>
        <template>
        <articleTheme :article="article"
                       :navItems="navItems"
                       />
        </template>
